Add make target for testing the database (using sql2csv from csvkit)

diff --git a/cron/Makefile b/cron/Makefile
--- a/cron/Makefile
+++ b/cron/Makefile
@@ -19,8 +19,16 @@ else
     PYTHON = python3
 endif
 
-.PHONY: all
-all: ${TABLES} ${IMPORTS} ${EXPORTS} /data/trades.db
+.PHONY: all \
+	tests \
+	test-min-rows-uf \
+	test-min-rows-ncm \
+	test-min-rows-import \
+	test-min-rows-export \
+	test-min-distinct-prod-import \
+	test-min-distinct-prod-export
+
+all: ${TABLES} ${IMPORTS} ${EXPORTS} /data/trades.db tests
 	echo "$@ success"
 
 # For an approach using curl, see https://stackoverflow.com/a/32703728/2062663
@@ -36,3 +44,79 @@ ${TABLES}: /data/%:
 	${PYTHON} scripts/createdb.py ${EXPORTS} --db=$@ --table=export && \
 	${PYTHON} scripts/createdb.py /data/NCM.csv --db=$@ --table=ncm --encoding=ISO-8859-1 && \
 	${PYTHON} scripts/createdb.py /data/UF.csv --db=$@ --table=uf --encoding=ISO-8859-1
+
+tests: test-min-rows-uf \
+	test-min-rows-ncm \
+	test-min-rows-import \
+	test-min-rows-export \
+	test-min-distinct-prod-import \
+	test-min-distinct-prod-export
+
+# Ensure the number of rows is at least the number of Brazilian states (26)
+test-min-rows-uf: /data/trades.db
+	@$(eval min_rows=26)
+	@$(eval n_rows=$(shell sql2csv -vH --db "sqlite:///$<" --query="SELECT COUNT(*) FROM uf"))
+	@if [ "$(n_rows)" -ge "$(min_rows)" ]; then \
+		echo "OK: There are at least $(min_rows) rows in table 'uf'"; \
+	else \
+		echo "ERROR: The table 'uf' has $(n_rows) rows but it should have at least $(min_rows)"; \
+		exit 1; \
+	fi
+
+# Ensure there are at least 6k products
+# (the current number is at least twice that value)
+test-min-rows-ncm: /data/trades.db
+	@$(eval min_rows=6000)
+	@$(eval n_rows=$(shell sql2csv -vH --db "sqlite:///$<" --query="SELECT COUNT(*) FROM ncm"))
+	@if [ "$(n_rows)" -ge "$(min_rows)" ]; then \
+		echo "OK: There are at least $(min_rows) product rows in table 'ncm'"; \
+	else \
+		echo "ERROR: The table 'uf' has $(n_rows) rows but it should have at least $(min_rows)"; \
+		exit 1; \
+	fi
+
+# Ensure there are at least 500k rows for each year
+# (the current numbers are at least twice that value)
+test-min-rows-import: /data/trades.db
+	@$(eval min_rows=500000)
+	@$(eval n_incomplete_years=$(shell sql2csv -vH --db "sqlite:///$<" --query="SELECT COUNT(*) c FROM (SELECT strftime(\"%Y\", DATA) year, COUNT(*) count FROM import GROUP BY year HAVING count < $(min_rows))"))
+	@if [ "$(n_incomplete_years)" -eq "0" ]; then \
+		echo "OK: There are at least $(min_rows) rows for each year in table 'import'"; \
+	else \
+		echo "ERROR: The table 'import' has fewer than $(min_rows) for some year"; \
+		exit 1; \
+	fi
+
+test-min-rows-export: /data/trades.db
+	@$(eval min_rows=500000)
+	@$(eval n_incomplete_years=$(shell sql2csv -vH --db "sqlite:///$<" --query="SELECT COUNT(*) c FROM (SELECT strftime(\"%Y\", DATA) year, COUNT(*) count FROM export GROUP BY year HAVING count < $(min_rows))"))
+	@if [ "$(n_incomplete_years)" -eq "0" ]; then \
+		echo "OK: There are at least $(min_rows) rows for each year in table 'export'"; \
+	else \
+		echo "ERROR: The table 'export' has fewer than $(min_rows) for some year"; \
+		exit 1; \
+	fi
+
+# Ensure at least ~30% of the products listed in 'ncm' table are present in the 'import' table
+# (the current percentage is >60%)
+test-min-distinct-prod-import: /data/trades.db
+	@$(eval min_percentage=30)
+	@$(eval percentage=$(shell sql2csv -vH --db "sqlite:///$<" --query="SELECT CAST(100 * (SELECT 1.0*COUNT(DISTINCT(CO_NCM)) FROM import) / (SELECT COUNT(*) count FROM ncm) AS INTEGER)"))
+	@if [ "$(percentage)" -ge "$(min_percentage)" ]; then \
+		echo "OK: At least $(min_percentage)% of the products from 'ncm' table are present in table 'import'"; \
+	else \
+		echo "ERROR: Less than $(min_percentage)% of the products from 'ncm' table are present in table 'import'"; \
+		exit 1; \
+	fi
+
+# Ensure at least ~30% of the products listed in 'ncm' table are present in the 'export' table
+# (the current percentage is >60%)
+test-min-distinct-prod-export: /data/trades.db
+	@$(eval min_percentage=30)
+	@$(eval percentage=$(shell sql2csv -vH --db "sqlite:///$<" --query="SELECT CAST(100 * (SELECT 1.0*COUNT(DISTINCT(CO_NCM)) FROM export) / (SELECT COUNT(*) count FROM ncm) AS INTEGER)"))
+	@if [ "$(percentage)" -ge "$(min_percentage)" ]; then \
+		echo "OK: At least $(min_percentage)% of the products from 'ncm' table are present in table 'export'"; \
+	else \
+		echo "ERROR: Less than $(min_percentage)% of the products from 'ncm' table are present in table 'export'"; \
+		exit 1; \
+	fi
